#     â–ˆâ–ˆâ•—      â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•— â–ˆâ–ˆâ•—  â–ˆâ–ˆâ•—â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—â–ˆâ–ˆâ•—  â–ˆâ–ˆâ•—â–ˆâ–ˆâ–ˆâ•—   â–ˆâ–ˆâ–ˆâ•—â–ˆâ–ˆâ•—â–ˆâ–ˆâ•—  â–ˆâ–ˆâ•— â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•— â–ˆâ–ˆâ–ˆâ•—   â–ˆâ–ˆâ•—â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•— â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—
#     â–ˆâ–ˆâ•‘     â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•—â–ˆâ–ˆâ•‘ â–ˆâ–ˆâ•”â•â–ˆâ–ˆâ•”â•â•â•â•â•â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ•‘â–ˆâ–ˆâ–ˆâ–ˆâ•— â–ˆâ–ˆâ–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘ â–ˆâ–ˆâ•”â•â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•—â–ˆâ–ˆâ–ˆâ–ˆâ•—  â–ˆâ–ˆâ•‘â•šâ•â•â–ˆâ–ˆâ•”â•â•â•â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•—
#     â–ˆâ–ˆâ•‘     â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•‘â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•”â• â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•‘â–ˆâ–ˆâ•”â–ˆâ–ˆâ–ˆâ–ˆâ•”â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•”â• â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•‘â–ˆâ–ˆâ•”â–ˆâ–ˆâ•— â–ˆâ–ˆâ•‘   â–ˆâ–ˆâ•‘   â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•‘
#     â–ˆâ–ˆâ•‘     â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•”â•â–ˆâ–ˆâ•— â•šâ•â•â•â•â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘â•šâ–ˆâ–ˆâ•”â•â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•”â•â–ˆâ–ˆâ•— â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘â•šâ–ˆâ–ˆâ•—â–ˆâ–ˆâ•‘   â–ˆâ–ˆâ•‘   â–ˆâ–ˆâ•”â•â•â–ˆâ–ˆâ•‘
#     â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•—â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ•—â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘ â•šâ•â• â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ•—â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ•‘â–ˆâ–ˆâ•‘ â•šâ–ˆâ–ˆâ–ˆâ–ˆâ•‘   â–ˆâ–ˆâ•‘   â–ˆâ–ˆâ•‘  â–ˆâ–ˆâ•‘
#     â•šâ•â•â•â•â•â•â•â•šâ•â•  â•šâ•â•â•šâ•â•  â•šâ•â•â•šâ•â•â•â•â•â•â•â•šâ•â•  â•šâ•â•â•šâ•â•     â•šâ•â•â•šâ•â•â•šâ•â•  â•šâ•â•â•šâ•â•  â•šâ•â•â•šâ•â•  â•šâ•â•â•â•   â•šâ•â•   â•šâ•â•  â•šâ•â•


# Don't print a new line at the start of the prompt
add_newline = false

# Make prompt a single line instead of two lines
[line_break]
disabled = false

# Replace the "â¯" symbol in the prompt with "âœ"
[character]                         # The name of the module we are configuring is "character"
success_symbol = "[  ->](bold #40f260)"  # The "success_symbol" is set to "âœ" with color "bold green"
error_symbol = "[  ->](bold #f24054)"      # used if previous command failed

########### Dracula Color  ################
[aws]
style = "bold #f2f260"

[git_branch]
format = " [$symbol$branch]($style) "
symbol = "ğŸ£ "
style = "bold #f240f2"

[git_commit]
commit_hash_length = 8
style = "bold #F2F280"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
conflicted = "âš”ï¸ "
ahead = "ğŸï¸ ğŸ’¨ Ã—${count}"
behind = "ğŸ¢ Ã—${count}"
diverged = "ğŸ”± ğŸï¸ ğŸ’¨ Ã—${ahead_count} ğŸ¢ Ã—${behind_count}"
untracked = "ğŸ›¤ï¸  Ã—${count}"
stashed = "ğŸ“¦ "
modified = "ğŸ“ Ã—${count}"
staged = "ğŸ—ƒï¸  Ã—${count}"
renamed = "ğŸ“› Ã—${count}"
deleted = "ğŸ—‘ï¸  Ã—${count}"
style = "bold #f24054"
format = "$all_status$ahead_behind"
#===============================================================

# Use custom format
#format = """
#[|](bold green)
#[â”‚](bold green)$directory$rust$package
#[â””â”€::](bold green) """

# ~/.config/starship.toml

#[shell]
#fish_indicator = "ïœ¹"
#powershell_indicator = "ï‘ _"
#unknown_indicator = "mystery shell"
#format = "[$indicator]($style) "
#style = "cyan bold"
#disabled = false


# Indicates when in bash shell.
#[custom.bash]
#command = "echo ğŸš€"
#when = '[ "$STARSHIP_SHELL" == "bash" ]'

# Indicates when in fish shell.
#[custom.fish]
#command = "echo ïœ¹"
#when = 'test "$STARSHIP_SHELL" = "fish"'

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[hostname]
ssh_only = false
format = "[$hostname]($style):: "
trim_at = "-"
style = "bold #00e5ff"
disabled = false

[memory_usage]
format = "$symbol[${ram}( | ${swap})]($style) "
threshold = 70
style = "bold dimmed white"
disabled = true

[time]
time_format = "%l:%M%P"
format = "$time($style) "
use_12hr = true
style = "bright-white"
disabled = true

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = " took [$duration]($style)"
style = "bold #f2f260"

[directory]
truncation_length = 3
format = "[$path]($style)[$lock_symbol]($lock_style) "
style = "bold #40f260"

# ~/.config/starship.toml

[username]
style_root = "bold #f240f2"
format = "[$user]($style) on "
style_user = "bold #f280c4"
disabled = true
show_always = true
